# Generated by Django 2.2.6 on 2019-11-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('s_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
    ]
